version: '3.8'

services:
  api_go:
    container_name: api_go
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "8181:8080"
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=api_go_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - mynetwork

  mysql:
    container_name: mysql_go
    image: mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "3308:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    networks:
      - mynetwork

  elasticsearch:
    container_name: elastic_go
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    networks:
      - mynetwork

volumes:
  db-data:
  elastic-data:

networks:
  mynetwork:
    driver: bridge
