version: '3.8'

services:
  api_go:
    container_name: api_go
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "8181:8080"
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=elasticgo
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - mynetwork

  mysql:
    container_name: mysql_go
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=api_go_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

  elasticsearch:
    container_name: elastic_go
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - mynetwork

volumes:
  db-data:
  es-data:

networks:
  mynetwork:
    driver: bridge
