# Etapa de construcción
FROM golang:1.21 as builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de módulos Go y descargar las dependencias
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copiar el resto de los archivos del proyecto
COPY ../ ./

# Compilar la aplicación Go.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api_go ./cmd/api

# Etapa de ejecución
FROM alpine:latest

# Instalar certificados CA
RUN apk --no-cache add ca-certificates

# Crear un usuario no root para ejecutar la aplicación
RUN adduser -D user
USER user

# Establecer el directorio de trabajo en el contenedor
WORKDIR /home/user

# Copiar el ejecutable compilado desde la etapa de construcción
COPY --from=builder /app/api_go .

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./api_go"]
